#!/bin/bash

if [ "$(id -u)" -ne 0 ]; then
  echo "This script must be run with sudo or as root. Please try again."
  exit 1
fi

dir="$(dirname "$0")"

pacman -Syu --noconfirm
pacman -S nginx --noconfirm
pacman -S ufw --noconfirm
useradd -r -m -d /var/lib/webgen -s /usr/sbin/nologin webgen
mkdir /var/lib/webgen/bin
cp "$dir/Data/generate_index" /var/lib/webgen/bin/generate_index
mkdir /var/lib/webgen/HTML
/var/lib/webgen/bin/generate_index
chown -R webgen:webgen /var/lib/webgen
chmod -R 777 /var/lib/webgen
cp "$dir/Data/generate-index.service" /etc/systemd/system/generate-index.service
cp "$dir/Data/generate-index.timer" /etc/systemd/system/generate-index.timer
cp "$dir/Data/nginx.conf" /etc/nginx/nginx.conf
mkdir /etc/nginx/sites-available 
mkdir /etc/nginx/sites-enabled
cp "$dir/Data/system-info.conf" /etc/nginx/sites-available/system-info.conf
ln -s /etc/nginx/sites-available/system-info.conf /etc/nginx/sites-enabled/system-info.conf
systemctl enable --now /etc/systemd/system/generate-index.service
systemctl enable --now /etc/systemd/system/generate-index.timer
systemctl enable --now nginx
systemctl enable --now ufw.service
ufw default deny incoming
ufw default allow outgoing
ufw allow ssh
ufw limit ssh
ufw allow http
echo "y" | ufw enable


systemctl daemon-reload
echo "Installation complete. Web server running. Index file will be updated at 5am daily."

